import { jsPDF } from "jspdf";

export const generatePDF = (userData, recommendations) => {
  const doc = new jsPDF();
  const { name, interest, level, goal } = userData;
  const { courses, roadmapSteps } = recommendations;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // Primary Blue
  doc.text("SERS: Learning Roadmap", 20, 20);
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42); // Dark Navy (almost)
  doc.text(`Student Name: ${name}`, 20, 35);
  doc.text(`Track: ${interest.toUpperCase()} (${level})`, 20, 42);
  doc.text(`Goal: ${goal.toUpperCase()}`, 20, 49);

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 55, 190, 55);

  // Recommended Courses
  doc.setFontSize(16);
  doc.text("Recommended Courses", 20, 65);
  
  doc.setFontSize(12);
  let yPos = 75;
  courses.forEach((course, index) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}. ${course.title}`, 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`   Provider: ${course.provider} | Duration: ${course.duration}`, 20, yPos + 7);
    yPos += 15;
  });

  // Roadmap with Tasks
  yPos += 10;
  doc.setFontSize(16);
  doc.text("Personalized Roadmap", 20, yPos);
  
  doc.setFontSize(11);
  yPos += 10;
  roadmapSteps.forEach((step, index) => {
    if (yPos > 250) { doc.addPage(); yPos = 20; }
    doc.setFont("helvetica", "bold");
    doc.text(`Step ${index + 1}: ${step.title}`, 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`   ${step.description}`, 20, yPos + 6);
    yPos += 12;
  });

  // Weekly Study Plan
  if (yPos > 220) { doc.addPage(); yPos = 20; }
  yPos += 10;
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text("4-Week Study Plan", 20, yPos);
  
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  yPos += 10;
  recommendations.studyPlan.forEach((week) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${week.week}: ${week.title}`, 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`   Topics: ${week.topics.join(", ")}`, 20, yPos + 6);
    yPos += 14;
  });

  // Skill Gap Analysis
  if (yPos > 240) { doc.addPage(); yPos = 20; }
  yPos += 10;
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text("Skill Gap Analysis", 20, yPos);
  
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  yPos += 10;
  recommendations.skillGap.forEach((skill) => {
    doc.text(`${skill.icon} ${skill.name}: ${skill.status}`, 20, yPos);
    yPos += 8;
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Smart E-Learning Recommendation System", 20, 280);

  doc.save(`${name.toLowerCase().replace(/ /g, '-')}-learning-roadmap.pdf`);
};
